[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.210"
solana-client = "2.0.10"
solana-sdk = "2.0.10"
sqlx = { version = "0.6.2", features = ["runtime-tokio-native-tls", "sqlite"] }
tokio = { version = "1.40.0", features = ["macros"] }
