CREATE TABLE games (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pubkey CHAR(32),
    host_key CHAR(32) NOT NULL UNIQUE
);

CREATE TABLE players (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pubkey CHAR(32) NOT NULL,
    game_key CHAR(32) NOT NULL,
    game_id INTEGER NOT NULL,
    role INTEGER NOT NULL,
    FOREIGN KEY(game_id) REFERENCES games(id)
);